substitutions:
  _ARTIFACT_REGISTRY_REPO: "microservices-repo"
  _LOCATION: "us-east1"
  _IMAGE_NAME: "REQUIRED_BUT_NOT_SET"
  _SERVICE_NAME: "REQUIRED_BUT_NOT_SET"
  _CI_CD_REPO_URL: "https://github.com/green-energy-tracker-cloud/ci-cd-templates.git"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  volumes:
    - name: 'maven-cache'
      path: '/root/.m2'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/sonar-cloud-token/versions/latest
      env: 'SONAR_CLOUD_TOKEN'

steps:
  - id: "Fetch Common Scripts"
    name: 'gcr.io/cloud-builders/git'
    args:
      - 'clone'
      - '--depth'
      - '1'
      - '_CI_CD_REPO_URL'
      - 'common-scripts'

  - id: "Unit Test"
    name: 'maven:3.9-eclipse-temurin-21'
    args: [ 'mvn', 'clean', 'test' ]

  - id: "Start Firestore"
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'run', '-d',
      '--network=cloudbuild',
      '--name=firestore',
      'gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators',
      'gcloud', 'emulators', 'firestore', 'start', '--project=local-project', '--host-port=0.0.0.0:8695'
    ]

  - id: "Start PubSub"
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'run', '-d',
      '--network=cloudbuild',
      '--name=pubsub',
      'gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators',
      'gcloud', 'beta', 'emulators', 'pubsub', 'start', '--project=local-project', '--host-port=0.0.0.0:8085'
    ]

  - id: "Start Redis"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'run', '-d', '--network=cloudbuild', '--name=redis', 'redis:alpine' ]

  - id: "Wait for Services"
    name: 'ubuntu'
    args: [ 'sleep', '15' ]
    waitFor: [ "Start Firestore", "Start Redis", "Start PubSub" ]

  - id: "Integration Test"
    name: 'maven:3.9-eclipse-temurin-21'
    env:
      - 'FIRESTORE_EMULATOR_HOST=firestore:8695'
      - 'PUBSUB_EMULATOR_HOST=pubsub:8085'
      - 'SPRING_DATA_REDIS_HOST=redis'
      - 'SPRING_DATA_REDIS_PORT=6379'
    args: [ 'mvn', 'verify', '-Dspring.profiles.active=local' ]
    waitFor:
      - "Wait for Services"

  - id: "Cleanup"
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker stop firestore pubsub redis || true'

  - id: "Load on Sonar Cloud"
    name: 'maven:3.9.4-eclipse-temurin-17'
    entrypoint: 'bash'
    args: [ 'common-scripts/ci/sonar_cloud_analysis.sh' ]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    secretEnv: [ 'SONAR_CLOUD_TOKEN' ]

  - id: "Push to Artifact Registry"
    name: 'gcr.io/cloud-builders/mvn'
    args: [
      'com.google.cloud.tools:jib-maven-plugin:3.4.5:build',
      '-Dimage=$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:$COMMIT_SHA',
      '-DskipTests'
    ]

  - id: "Check Vulnerabilities"
    name: 'gcr.io/google.com/cloudsdktool/google-cloud-cli'
    entrypoint: 'bash'
    args: ['common-scripts/ci/check_vulnerabilities.sh']
    env:
      - 'LOCATION=$_LOCATION'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'ARTIFACT_REGISTRY_REPO=$_ARTIFACT_REGISTRY_REPO'
      - 'IMAGE_NAME=$_IMAGE_NAME'
      - 'COMMIT_SHA=$COMMIT_SHA'

  - id: "Create Release"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      - 'rel-${SHORT_SHA}'
      - '--delivery-pipeline=delivery-pipeline'
      - '--region=us-east1'
      - '--source=./cd/'
      - '--images=$_SERVICE_NAME=$_LOCATION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO/$_IMAGE_NAME:${COMMIT_SHA}'